config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  root "movies#index"

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  belongs_to :user
  has_many :reviews

  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  searchkick
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    if @movie.reviews.blank?
      @avg_review = 0
    else
      @avg_review = @movie.reviews.average(:rating).round(2)
    end

  end

  # GET /movies/new
  def new
    # @movie = Movie.new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    # @movie = Movie.new(movie_params)
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].present?
      @movies = Movie.search(params[:search])
    else
      @movies = Movie.all
    end
    puts @movies
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :user_id, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :authenticate_user!

  respond_to :html

  def index
    @reviews = Review.all
    respond_with(@reviews)
  end

  def show
    respond_with(@review)
  end

  def new
    # @review = Review.new
    @review = current_user.reviews.build
    respond_with(@review)
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id
    @review.save
    redirect_to @movie #movie_path(@movie.id)
    # respond_with(@review)
  end

  def update
    @review.update(review_params)
    redirect_to movie_path(@movie)
    # respond_with(@review)
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapsed" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Movie Reviews", root_path , class: "navbar-brand") %>
    </div>

    <!-- Collect the nav link, forms and other content for toggling -->
    <div class="collapse navbar-collapse" id="#bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to("New Movie", new_movie_path, class: "active") %></li>
          <li><%= link_to("Account", edit_user_registration_path) %></li>
        <% else %>
          <li><%= link_to("Sign Up", new_user_registration_path, class: "active") %></li>
          <li><%= link_to("Sign In", new_user_session_path , class: "active") %></li>
        <% end %>
      </ul>
      <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div> <!-- /.container -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieRating</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, :class => "alert alert-danger") %>
    <% end %>

    <%= yield %>

    <hr>
    <footer>Copyright @2014 Ermand Duro</footer>
  </div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true , class: "form-horizontal"} do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "control-label col-sm-3" %><br>
    <div class="col-sm-6">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "control-label col-sm-3" %><br>
    <div class="col-sm-6">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :movie_length, class: "control-label col-sm-3" %><br>
    <div class="col-sm-6">
      <%= f.text_field :movie_length, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :director, class: "control-label col-sm-3" %><br>
    <div class="col-sm-6">
      <%= f.text_field :director, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rating, class: "control-label col-sm-3" %><br>
    <div class="col-sm-6">
      <%= f.text_field :rating, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, class: "control-label col-sm-3" %><br>
    <%= f.file_field :image %>
  </div>

  <div class="row">
    <div class="col-xs-6 col-sm-12 col-sm-offset-3 col-xs-offset-3">
      <div class="btn-toolbar">
        <%= submit_tag("Submit", {:class => 'btn btn-primary'}) %>
      </div>
    </div>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie, class: "btn btn-default" %> |
<%= link_to 'Back', movies_path, class: "btn btn-default" %>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Your favorited movies Reviewed</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt molestias ad dolore, odit. Unde ea ut inventore voluptate. Magni cumque rem ratione. Est numquam eius eveniet ullam. Id, pariatur, dolor.</p>
    <%= link_to("Sign Up To Write A Review", new_user_registration_path , class: "btn btn-primary btn-lg") %>
  </div>
<% end %>
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium), class: "image"), movie %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path, class: "btn btn-default" %>

app/views/movies/search.html.erb
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium), class: "image"), movie %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to 'Back', movies_path, class: "btn btn-info btn-sm" %> |
    <%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-default btn-sm" %> |
    <%= link_to 'New Review', new_movie_review_path(@movie), class: "btn btn-success btn-sm" %>
    <hr>

    <div class="row">
      <div class="col-md-4">
        <%= image_tag @movie.image.url(:medium), size: "200x300" %>
        <div class="star-rating" data-score=<%= @avg_review %>></div>
        <em><%= "#{@movie.reviews.length} reviews" %></em>
      </div> <!-- /.col-md-4 -->

      <div class="col-md-6">
        <div class="table-responsible">
          <table class="table table-hover table-condensed">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @movie.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @movie.description %></td>
              </tr>
              <tr>
                <td><strong>Movie length:</strong></td>
                <td><%= @movie.movie_length %></td>
              </tr>
              <tr>
                <td><strong>Director:</strong></td>
                <td><%= @movie.director %></td>
              </tr>
              <tr>
                <td><strong>Rating:</strong></td>
                <td><%= @movie.rating %></td>
              </tr>
              <tr>
                <td><strong>User:</strong></td>
                <td><%= @movie.user_id %></td>
              </tr>
            </tbody>
          </table>
        </div> <!-- /.table-responsible -->
      </div> <!-- /.col-md-6 -->
    </div>

    <div class="row">
      <div class="col-md-12">
      <h2>Reviews</h2>
      <% if @movie.reviews.blank? %>
        <h3>No reviews just yet, would you like to add the first!</h3>
        <%= link_to 'Write Review', new_movie_review_path(@movie), class: "btn btn-danger btn-sm" %>
      <% else %>
        <% @movie.reviews.each do |review| %>
          <div class="reviews">
            <div class="star-rating" data-score=<%= review.rating %>> </div>
            <p><%= review.comment %></p>
            <p><%= link_to 'Edit', edit_movie_review_path(@movie.id, review), class: "btn btn-primary btn-xs" %></p>
          </div>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score')
    }
  })
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="row">
    <div class="col-xs-6 col-sm-12">
      <div class="btn-toolbar">
        <%= submit_tag("Submit", {:class => 'btn btn-primary'}) %>
      </div>
    </div>
  </div>
<% end %>
<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  })
</script>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_path(@movie), class: "btn btn-sm btn-default" %>

app/views/reviews/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row ">
      <h1>Listing reviews</h1>
      <%= link_to 'New Review', new_review_path, class: "btn btn-success btn-sm" %>
      <table class="table">
        <thead>
          <tr>
            <th>Rating</th>
            <th>Comment</th>
            <th>User</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @reviews.each do |review| %>
            <tr>
              <td><%= review.rating %></td>
              <td><%= review.comment %></td>
              <td><%= review.user.email %></td>
              <td><%= link_to 'Show', review, class: "btn btn-info btn-xs" %></td>
              <td><%= link_to 'Edit', edit_review_path(review), class: "btn btn-primary btn-xs" %></td>
              <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_path(@movie), class: "btn btn-default btn-sm" %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review), class: "btn btn-sm btn-default" %> |
<%= link_to 'Back', reviews_path, class: "btn btn-sm btn-default" %>